#!/usr/bin/env bash
# ngensite (github:jusdepatate/shell-tools)
# a2ensite but for nginx

fatal() {
  echo "$*"
  exit 1
}

if [ "$EUID" -ne 0 ]; then
    fatal "Please, execute as root."
fi

if [ "$1" = "" ]; then
  fatal "No argument found"
fi

source="$(echo /etc/nginx/sites-available/"$*".conf | sed "s/.conf.conf/.conf/")"
desto="$(echo /etc/nginx/sites-enabled/"$*".conf | sed "s/.conf.conf/.conf/")"
# little hack in case argument contains .conf (or not)

if [ ! -f "$source" ]; then
  fatal "$source doesn't exist"
elif [ -f "$desto" ]; then
  fatal "$desto already exists"
fi

ln -s "$source" "$desto" || fatal

if [ "$(nginx -t &>/dev/null)" ]; then
  systemctl restart nginx
else
  fatal "$(nginx -t)"
fi