#!/usr/bin/env bash
# Hiber [File/Link] CLI Client
# Jus de Patate - 2020

version="1.0"

hiberfile="https://hiberfile.com"
hiberlink="https://hiber.link"

link() {
	curl -s -X POST "$hiberlink/link.php" --data "link=$1"
	echo ""  # tiny hack to add a line return because hiberlink doesnt
}

file() {
	res="$(curl -X POST -s -F"my_file=@$1" -F"time=7 jours" "$hiberfile/send.php")"
	
	echo "$res" | grep "fileToUpload" | grep -o "value=\".*\"" | sed 's/value="//' | sed 's/"//'
	echo ""
}

# shellcheck disable=SC2143
if [ -z "$1" ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
	echo "Hiber Client for CLI - Jus de Patate - $version"
	echo "HiberFile instance is set at $hiberfile"
	echo "HiberLink instance is set at $hiberlink"
	echo ""
	echo "Please use either a file or an url as command argument"
elif [ -f "$1" ]; then
	file "$1"
elif [ "$(echo "$1" | grep "^.*[.].*$")" ]; then
	link "$1"
else
	echo "Unrecognized argument"
fi
